// src/worlds/worlds.js

export const VIEWPORT_WIDTH = 1400;
export const VIEWPORT_HEIGHT = 680;

// Big scrollable world
export const WORLD_WIDTH = 2000;
export const WORLD_HEIGHT = 2000;

export const WORLDS = {
  nexus: {
    id: "nexus",
    title: "Experience Select",
    description: "Walk up to a portal and press SPACE to enter that world.",
    backgroundClass: "world-bg-nexus",
    playerSkin: "nexus",
    width: 2000,
    height: 1200,
    spawn: { x: 100, y: 840 },
    timeline: [
      { year: 2016, x: 150 },
      { year: 2020, x: 400 },
      { year: 2021, x: 650 },
      { year: 2022, x: 900 },
      { year: 2023, x: 1150 },
      { year: 2024, x: 1400 },
      { year: 2025, x: 1650 },
      { year: 2026, x: 1900 },
    ],
    npcs: [
      {
        id: "mentor",
        title: "Guide",
        x: 900,
        y: 680,
        width: 28,
        height: 32,
        lines: [
          "Welcome to the Nexus.",
          "Portals unlock with keys you earn from XP.",
          "Collect all artifacts in a world for a badge.",
        ],
      },
      {
        id: "lorekeeper",
        title: "Lorekeeper",
        x: 760,
        y: 680,
        width: 28,
        height: 32,
        lines: [
          "Each world hides 3 artifacts.",
          "Step over them to collect.",
          "100% a world to show its badge.",
        ],
      },
      {
        id: "guide",
        title: "PortalTech",
        x: 1040,
        y: 680,
        width: 28,
        height: 32,
        lines: [
          "SPACE to talk/enter portals, ENTER for inventory.",
          "Backspace returns you to the Nexus.",
          "Keys open new portals.",
        ],
      },
    ],
    portals: [
      {
        id: "meneses",
        label: "Meneses Law (current)",
        x: 1350,
        y: 800,
        width: 140,
        height: 90,
      },
      {
        id: "eit",
        label: "EIT Care",
        x: 1175,
        y: 820,
        width: 140,
        height: 70,
      },
      {
        id: "kartocars",
        label: "KartoCars",
        x: 625,
        y: 820,
        width: 160,
        height: 70,
      },
      {
        id: "chronospel",
        label: "ChronoSpel",
        x: 450,
        y: 820,
        width: 140,
        height: 70,
      },
      {
        id: "gjhmail",
        label: "GJHMail (Current)",
        x: 1750,
        y: 800,
        width: 140,
        height: 90,
      },
      {
        id: "university",
        label: "University",
        x: 250,
        y: 820,
        width: 140,
        height: 70,
      },
      {
        id: "trial10",
        label: "Trial Gate",
        x: 10,
        y: 10,
        width: 150,
        height: 70,
        requiresLevel: 10,
        hideRequirementHint: true,
      },
      {
        id: "badgehall",
        label: "Badge Gate",
        x: 1820,
        y: 10,
        width: 170,
        height: 70,
        requiresAllBadges: true,
        hideRequirementHint: true,
      },
      {
        id: "mastergate",
        label: "Master Gate",
        x: 900,
        y: 10,
        width: 200,
        height: 80,
        requiresBothKeys: true,
        hideRequirementHint: true,
      },
    ],
  },
  meneses: {
    id: "meneses",
    title: "Meneses Law",
    description:
      "Immigration law firm where I built internal automation and full-stack tools.",
    backgroundClass: "world-bg-meneses",
    playerSkin: "meneses",
    width: 1900,
    height: 1400,
    spawn: { x: 960, y: 900 },
    npcs: [
      {
        id: "extra",
        title: "UI-Extra",
        x: 440,
        y: 1200,
        width: 56,
        height: 64,
        lines: [
          "Here we finally got a dedicated UI/UX developer and Figma usage.",
          "The new developer created a bunch of designs for components, headers, sidebars, etc.",
          "It was fun using story book to create a nice way of viewing and demonstrating how each component looks and is used.",
        ],
      },
      {
        id: "extra",
        title: "Onnoarding-Extra",
        x: 1750,
        y: 630,
        width: 56,
        height: 64,
        lines: [
          "This was my second project I worked on at Meneses Law but it was the first project that I was the owner of.",
          "This project was insanely difficult not only because its complexity but also because of the siloh I was in when trying to communicate with other departments.",
          "Due to how all many things werent standardized I had to make a lot of un optimised desicions to make the automation work within the current system and abide to the obscure requirements.",
          "In the end it took a long time and a lot of fires to put out but it finally deployed and over time updated to something worth it.",
        ],
      },
      {
        id: "extra",
        title: "Extra",
        x: 1040,
        y: 110,
        width: 56,
        height: 64,
        lines: [
          "This project was a lot of fun because at the time we weren’t using EC2 instances, and I didn’t yet know that AWS API Gateway supported WebSockets. After doing some deeper research, I realized I could build a lightweight real-time system using AWS SNS in a pub/sub pattern.",
          "The idea was simple but effective: every new mobile device registered with the app had its unique device ID, which I stored in MongoDB, then subscribed to an SNS topic. Then, inside our internal messaging dashboard, whenever a team member selected a client and sent them a message, the backend would look up that client’s stored device ID(s) and publish a notification to SNS with the message content in the payload. SNS would immediately push that payload to the client’s phone app, allowing the message to appear almost in real-time — all without needing WebSockets or dedicated servers.",
          "It was a creative workaround that gave us real-time messaging using only serverless components.",
        ],
      },
    ],
    blockedZones: [
      { x: 0, y: 0, width: 320, height: 1400 },
      { x: 320, y: 0, width: 180, height: 420 },
      { x: 1400, y: 0, width: 500, height: 360 },
      { x: 1300, y: 1040, width: 600, height: 360 },
    ],
    collectibles: [
      {
        id: "brief-1",
        label: "Case Note",
        icon: "✦",
        x: 880,
        y: 760,
        width: 18,
        height: 18,
      },
      {
        id: "brief-2",
        label: "Filing",
        icon: "✦",
        x: 1100,
        y: 520,
        width: 18,
        height: 18,
      },
      {
        id: "brief-3",
        label: "Badge",
        icon: "✦",
        x: 1500,
        y: 960,
        width: 18,
        height: 18,
      },
    ],

    // 🖥️ In-world terminals (readable with SPACE)
    terminals: [
      {
        id: "meneses",
        x: 905,
        y: 800,
        width: 140,
        height: 90,
        title: "Lore",
        lines: [
          "- I started working as a Full Stack Developer at Meneses Law since December 18, 2023.",
          "- This was my first REAL job outside of school and I wasn't the most confident in my coding abilities.",
          "- This is where I really got the experience and was able to hone my abilities as a Full Stack Developer.",
          "- As you journey forward you'll see I was luckily able to work on many different types of projects.",
          "- I will say, my favorite part of working at Meneses Law is my co-workers, we're all super close now and I consider them worthy of the title Friend :)",
        ],
      },
      {
        id: "meneses",
        x: 905,
        y: 600,
        width: 140,
        height: 90,
        title: "Skills/Tech Stack",
        lines: [
          "Front End",
          "- React, React Native, CSS, Tailwind, TypeScript",
          "Back End",
          "- Node, Bun,TypeScript, FastApi, Python, Prisma, Zod",
          "Cloud Services",
          "- AWS (Lambda, EC2, API Gateway CloudWatch, S3, SES, SNS,  SecretsManager, Cognito, Bedrock)",
          "- Azure (Entra Id, Graph API)",
          "Database",
          "- NoSQL MongoDB",
        ],
      },
      {
        id: "meneses",
        x: 1000,
        y: 180,
        width: 140,
        height: 90,
        title: "Secure Mobile App",
        lines: [
          "Built a secure iOS + Android app.",
          "For sending encrypted PII and direct messages from client to lawyer.",
          "Designed to integrate smoothly into our current client sign up process",
          "React Native • AWS • MongoDB.",
        ],
      },
      {
        id: "meneses",
        x: 1600,
        y: 600,
        width: 140,
        height: 90,
        title: "Onboarding Automation",
        lines: [
          "Automated employee onboarding & offboarding",
          "Onboarding would automatically create employees in MongoDB, Azure Entra Id, assign roles, groups, and licenses.",
          "Offboarding would disable employees in Mongo and disable Azure users, remove groups, and licenses.",
          "React • PowerShell • Entra ID • AWS Lambda",
        ],
      },
      {
        id: "meneses",
        x: 350,
        y: 450,
        width: 140,
        height: 90,
        title: "Call → Consultation",
        lines: [
          "Turned multi-hour phone calls into structured consultation forms.",
          "Used GOTO API to push finished phone calls to an S3 bucket, integrated AI for speech to text to create a transcript, then use the transcript to create an emotional abuse story and a Cover letter, formatted and converted to a doc, saved a Spanish translated version, then saved and pushed to lawyers for check.",
          "React • NoSQL • AWS Lambda • Amazon Bedrock • S3",
        ],
      },
      {
        id: "meneses",
        x: 1750,
        y: 850,
        width: 140,
        height: 90,
        title: "Complicated Algorithm",
        lines: [
          "This was a super fun project, this was the first project the entire team worked on together, everyone would get together to brainstorm ideas on the most effecient way to flow all the peices together then actually work together on all parts to make sure everything would connect together by the end.",
          "I initially with a co-worker worked on the front end initial start until it would be fully automated with the api, it was simple but had drop downs to select clients, drag and drop to upload audio files, and a recorder just incase the interview happened in office and not over the phone.",
          "In the backend I worked on a bit of everything but the main things I remember working on alone was formatting and creating the docx from the txt transcript.",
          "And the most complicated looking parser was created here -> :O",
        ],
      },
      //       export const parser = (rawText: string) => {
      //   const lines = getLines(rawText);
      //   const result: ParsedResult = { INTRODUCTION: { 0: "" } };
      //   let currentSection: string = INTRODUCTION_HEADER;
      //   let currentNumber = 0;

      //   const removeEndingQuote = () => {
      //     if (result?.[currentSection]?.[currentNumber]) {
      //       result[currentSection][currentNumber] =
      //         result[currentSection][currentNumber].trim();
      //       // Remove any trailing quote (", “, or ”)
      //       result[currentSection][currentNumber] = result[currentSection][
      //         currentNumber
      //       ].replace(/["“”]$/, "");
      //     }
      //   };
      //   lines.forEach((line) => {
      //     const trimmedLine = line.trim();
      //     const tabMatch = TAB_REGEX.exec(trimmedLine);
      //     const sectionMatch = SECTION_HEADINGS_REGEX.exec(trimmedLine);
      //     if (tabMatch) {
      //       removeEndingQuote();
      //       currentNumber += 1;
      //       if (currentSection) result[currentSection][currentNumber] = "";
      //     }
      //     if (sectionMatch) {
      //       removeEndingQuote();
      //       currentSection = sectionMatch[1];
      //       if (!result[currentSection]) {
      //         result[currentSection] = {};
      //       }
      //     } else {
      //       const removedTab = trimmedLine.replace("> ", "").replace(/^["“”]/, "");
      //       result[currentSection][currentNumber] += removedTab + " ";
      //     }
      //   });
      //   removeEndingQuote();
      //   return result;
      // };

      {
        id: "meneses",
        x: 400,
        y: 1100,
        width: 140,
        height: 90,
        title: "UI Component Library",
        lines: [
          "Built internal Storybook library.",
          "Improved designer-dev workflow and",
          "reduced duplicate front-end code",
          "by about 25%.",
        ],
      },
      {
        id: "meneses",
        x: 1000,
        y: 1260,
        width: 140,
        height: 90,
        title: "Lambda Upgrades",
        lines: [
          "Upgraded 10+ AWS Lambda funcs",
          "from deprecated Node runtimes",
          "to modern TS + Tailwind stacks.",
          "Improved maintainability & AWS",
          "support going forward.",
        ],
      },
    ],
  },
  eit: {
    id: "eit",
    title: "EIT Care",
    description:
      "Support Engineer work — servers, uptime, and cross-company IT operations.",
    backgroundClass: "world-bg-eit",
    playerSkin: "eit",
    width: 1400,
    height: 1200,
    spawn: { x: 960, y: 900 },
    blockedZones: [
      { x: 0, y: 0, width: 1400, height: 260 },
      { x: 0, y: 260, width: 240, height: 940 },
      { x: 1150, y: 260, width: 250, height: 940 },
    ],
    collectibles: [
      {
        id: "chip-1",
        label: "Server Chip",
        icon: "◆",
        x: 820,
        y: 820,
        width: 18,
        height: 18,
      },
      {
        id: "chip-2",
        label: "Patch Disk",
        icon: "◆",
        x: 300,
        y: 320,
        width: 18,
        height: 18,
      },
      {
        id: "chip-3",
        label: "Network Key",
        icon: "◆",
        x: 450,
        y: 1040,
        width: 18,
        height: 18,
      },
    ],
    terminals: [
      {
        id: "eit",
        x: 625,
        y: 700,
        width: 140,
        height: 90,
        title: "Lore",
        lines: [
          "I started working at EIT as a Support Engineer after Mardi Gras of 2023, finding a job in my field was hard and I was desperate to get anything under my belt.",
          "Even though this wasn't a software job I needed money and didn't want to have a gap of no work in my resume.",
          "EIT Care was a small company focused primarily on setting up and maintaining businesses with servers, security, and employee management.",
          "My experience here was great because it was very client facing, as I would have to drive to physical locations to set up or fix many problems.",
          "Due to this I was able to build a strong set of connections with peopel from many different backgrounds including Law firms, Geophysics Industries, Clothing Manufacturers and many more.",
        ],
      },
      {
        id: "eit",
        x: 625,
        y: 500,
        width: 140,
        height: 90,
        title: "Skills Gained",
        lines: [
          "- Client facing communication",
          "- Fixing issues in real time under pressure",
          "- Microsoft Active Directory",
          "- Building servers",
          "- Maintenance of hardware (Servers, Switches, Printers, Scanners, Fax Machines, Land Line Phones)",
        ],
      },
      {
        id: "eit",
        x: 325,
        y: 700,
        width: 140,
        height: 90,
        title: "Client IT Ops",
        lines: [
          "Supported 3 client companies,",
          "25+ staff each, handling IT issues.",
          "Increased systems uptime by ~35%",
          "and noticeably boosted productivity.",
        ],
      },
      {
        id: "eit",
        x: 925,
        y: 700,
        width: 140,
        height: 90,
        title: "Server Deployments",
        lines: [
          "Engineered and deployed 2 dedicated",
          "servers and domains for new clients.",
          "Gave them a strong digital presence",
          "and ~20% better operational agility.",
        ],
      },
      {
        id: "eit",
        x: 625,
        y: 900,
        width: 140,
        height: 90,
        title: "Cross-Functional Work",
        lines: [
          "Collaborated with managers and",
          "teams across several industries.",
          "Improved cross-functional",
          "collaboration and relationships.",
        ],
      },
    ],
  },
  kartocars: {
    id: "kartocars",
    title: "KartoCars",
    description:
      "Retrowave car world: blockchain website, NFTs, and team leadership.",
    backgroundClass: "world-bg-kartocars",
    playerSkin: "kartocars",
    width: 1800,
    height: 1600,
    spawn: { x: 960, y: 250 },
    blockedZones: [
      { x: 0, y: 0, width: 1800, height: 220 },
      { x: 0, y: 220, width: 260, height: 1380 },
      { x: 1560, y: 220, width: 240, height: 1380 },
      { x: 260, y: 700, width: 685, height: 160 },
      { x: 1000, y: 700, width: 560, height: 160 },
      { x: 260, y: 1460, width: 1300, height: 100 },
    ],
    collectibles: [
      {
        id: "spark-1",
        label: "Turbo Coin",
        icon: "⬤",
        x: 965,
        y: 760,
        width: 18,
        height: 18,
      },
      {
        id: "spark-2",
        label: "Neon Shard",
        icon: "⬤",
        x: 1460,
        y: 250,
        width: 18,
        height: 18,
      },
      {
        id: "spark-3",
        label: "Track Pass",
        icon: "⬤",
        x: 1540,
        y: 1370,
        width: 18,
        height: 18,
      },
    ],
    terminals: [
      {
        id: "kartocars",
        x: 905,
        y: 300,
        width: 140,
        height: 90,
        title: "Karto Lore",
        lines: [
          "It all started with me and my cousin back when we were still in college, nfts were popping off and we wanted to join the hype to get rich quick.",
          "It actually started as a weird luck of the draw buy our nfts and try connecting them to make a map with a treasure hinted somewhere in it. With the back of the cards having gold, stone, wood, or a sheep, all giving some default prize.",
          "It quickly changed into a mix of the two things we both liked most at the time, I was huge into retrowave 80's music and art style, and he was getting really into cars. So we created KartoCars!",
        ],
      },
      {
        id: "kartocars",
        x: 905,
        y: 400,
        width: 140,
        height: 90,
        title: "Karto Lore Pt.2",
        lines: [
          "KartoCars is a retrowave Play to Earn (p2e) project of 10,000 unique styled cars with 15 different body types and each body consisting of interchangable cosmetics to make sure each car was completely its own.",
          "It started off small, just me and my cousin building this thing from scratch, I was working part time while going to school to supply money for any investment that he was stirring up.",
          "eventually we end up with a team, a discord, and an actual vision",
        ],
      },
      {
        id: "kartocars",
        x: 1055,
        y: 300,
        width: 140,
        height: 90,
        title: "Karto Game",
        lines: [
          "The KartoCars game was released on the same day as the NFTs minted, its a play to earn game meaning you would earn karto tokens as you play.",
          "You could use tokens to buy in game boosts, unlock new maps, and bet on live tournaments against other players.",
          "When you launch the game, you would connect it with your cold wallet and get to play as the KartoCars you minted and stored in your wallet.",
          "Each car had different specs based on the rarity of the car you pulled.",
          "The game launched with 1 map with plans of updating as the project continued growing!",
        ],
      },
      {
        id: "kartocars",
        x: 755,
        y: 300,
        width: 140,
        height: 90,
        title: "Karto Team",
        lines: [
          "Matthew Klayme -> Co-Owner/Founding Developer",
          "Najib El Hayek -> Co-Owner/Financial Advisor",
          "PWine -> CMO",
          "NFTTerrance -> Web Developer/Discord Mod/ Content Creator",
          "Greg Smith (alpha goose) -> Video Game Developer",
          "Tipping Toast Media -> 3D Modelers/Audio",
          "Ashley and Chad -> Artist",
        ],
      },
      {
        id: "kartocars",
        x: 905,
        y: 980,
        width: 140,
        height: 90,
        title: "Blockchain Website",
        lines: [
          "Designed & developed a web3 site.",
          "Improved client engagement by 30%",
          "and smoothed smart contract",
          "interactions on Ethereum.",
        ],
      },
      {
        id: "kartocars",
        x: 1055,
        y: 1070,
        width: 140,
        height: 90,
        title: "NFT Collection",
        lines: [
          "Generated 2,500 unique art pieces",
          "with JSON attributes.",
          "Expanded digital portfolio and",
          "boosted brand visibility.",
        ],
      },
      {
        id: "kartocars",
        x: 755,
        y: 1070,
        width: 140,
        height: 90,
        title: "Team Leadership",
        lines: [
          "Co-founded KartoCars and led a",
          "10-person multi-disciplinary team.",
          "Boosted project completion",
          "efficiency by about 80%.",
        ],
      },
      {
        id: "kartocars",
        x: 905,
        y: 1160,
        width: 140,
        height: 90,
        title: "Mobile Racing Game",
        lines: [
          "KartoCars Racing game was release on the IOS app store and is still up and downloadable today.",
          "The game has a classic retrowave asthetic with a beautiful original sound track.", // put a clickable link to it
          "The game was released with a Time Trial Mode.",
          "KartoCars sadly was never continued due to project cancellation.",
        ],
      },
      {
        id: "kartocars",
        x: 1420,
        y: 1270,
        width: 140,
        height: 90,
        title: "Travel",
        lines: [
          "Because KartoCars a part of a very much a community based sect, so much of what I had to do was travel, attend events, and meet new people.",
          "- SXSW",
          "Where we met with the bunnies (another project) collaborated with them, and through them collaborated with cloud ppl, ",
          "We got invited to attent the bunny launch party where they build an entire dome with the inside walls being entirely screen and hired a famouse(find who) dj to play with them",
          "- DeCentral",
          "At DeCentral I was actually able to shill my project to a lot of others in the community, became friends with a lot of content creators and speakers in the space.",
          "From the connections I made at DeCentral I was invited to speak at a conference in Florida but due to circumstances I wasnt able to make that one :(",
        ],
      },
      {
        id: "kartocars",
        x: 300,
        y: 1270,
        width: 140,
        height: 90,
        title: "Discord Nights",
        lines: [
          "- Discord Nights",
          "Every Tuesday night was Discord Game Night, this was a community bonding experience where the team and anyone in the community would hop in a voice call and play multiplayers games together, listen to music, and just talk about the project and its ideas/upcoming plans",
        ],
      },
    ],
  },
  chronospel: {
    id: "chronospel",
    title: "ChronoSpel",
    description:
      "A magical automation world where time, schedules, and tasks obey your command.",
    backgroundClass: "world-bg-chronospel",
    playerSkin: "chronospel",
    width: 1500,
    height: 1600,
    spawn: { x: 960, y: 900 },
    blockedZones: [
      // upper void
      { x: 0, y: 0, width: 1500, height: 280 },
      // left pillar
      { x: 0, y: 280, width: 240, height: 1320 },
      // right pillar
      { x: 1260, y: 280, width: 240, height: 1320 },
      // center pit
      { x: 520, y: 980, width: 460, height: 200 },
    ],
    collectibles: [
      {
        id: "rune-1",
        label: "Rune",
        icon: "✧",
        x: 840,
        y: 880,
        width: 18,
        height: 18,
      },
      {
        id: "rune-2",
        label: "Scroll",
        icon: "✧",
        x: 700,
        y: 1350,
        width: 18,
        height: 18,
      },
      {
        id: "rune-3",
        label: "Crystal",
        icon: "✧",
        x: 1080,
        y: 1180,
        width: 18,
        height: 18,
      },
    ],

    terminals: [
      {
        id: "chrono",
        x: 705,
        y: 750,
        width: 140,
        height: 90,
        title: "Chrono Lore",
        lines: [
          "When the project first started I was super into developing video games, it was the reason I got in Computer Science in the first place, and I really wanted to use a team to help me create a game in my taste.",
          "So when teams were picked I instantly chose to be the leader because I wanted to make all the design and development decisions.",
          "I had designed a souls-like game because Dark Souls had made a huge impact on my opinion on video games and what made a game good.",
          "I called the game Chrono Spel, and it was going to be developed using Unreal Engine 4.",
        ],
      },
      {
        id: "chrono",
        x: 705,
        y: 850,
        width: 140,
        height: 90,
        title: "The Incident",
        lines: [
          "A week into the semester I broke my clavicle in an unfortunate event, and I was gone from school for about 3 weeks.",
          "On my return the team shifted, we got a new leader, a new vision, and everything came crashing.",
          "The game had shifted to a VR game where you were an immobile turret in space that would shoot incoming asteroids and space pirates to defend base.",
          "Sadly for everyone besides the new leader, no one had a VR head set, so testing was very difficult.",
          "Overall a dissapointing outcome.",
        ],
      },
      {
        id: "chrono",
        x: 755,
        y: 1250,
        width: 140,
        height: 90,
        title: "Time Scheduler Engine",
        lines: [
          "Built and designed the automated wave spawner.",
          "Enemy Entities would spawn at random location spots, and at random times.",
          "Waves would increasingly get harder by increasing spawn cap and time between new spawns.",
        ],
      },
      {
        id: "chrono",
        x: 755,
        y: 1350,
        width: 140,
        height: 90,
        title: "Frontend Spellbook",
        lines: [
          "Utilized Unreal Engines Animations to create a into cutscene for the game menu.",
          "Used Blendr to create, model, and skin entities such as Plantes, Space Crafts, and Asteroids",
        ],
      },
    ],
  },
  gjhmail: {
    id: "gjhmail",
    title: "GJHMail Automation",
    description:
      "Automated Gmail → AI → documents → replies pipeline with Pub/Sub and AWS/GCP.",
    backgroundClass: "world-bg-gjhmail",
    playerSkin: "gjhmail",
    width: 1700,
    height: 1200,
    spawn: { x: 960, y: 900 },
    blockedZones: [
      { x: 0, y: 0, width: 1700, height: 180 },
      { x: 0, y: 180, width: 260, height: 1020 },
      { x: 1440, y: 180, width: 260, height: 1020 },
      { x: 700, y: 760, width: 260, height: 240 },
    ],
    collectibles: [
      {
        id: "mail-1",
        label: "Envelope",
        icon: "✉",
        x: 520,
        y: 820,
        width: 18,
        height: 18,
      },
      {
        id: "mail-2",
        label: "Parser Chip",
        icon: "✉",
        x: 1160,
        y: 820,
        width: 18,
        height: 18,
      },
      {
        id: "mail-3",
        label: "Auto-Reply",
        icon: "✉",
        x: 1400,
        y: 940,
        width: 18,
        height: 18,
      },
    ],

    terminals: [
      {
        id: "gjhmail",
        x: 450,
        y: 1000,
        width: 140,
        height: 90,
        title: "GJHMail Lore",
        lines: [
          "GJHMail started sometime mid 2024 as a concept idea",
          "Due to my experience and time in Meneses Law I managed to meet and get to know a good amount of lawyers.",
          "After talking to one of them, he had an idea that would make his life a whole lot easier, and me being a developer offered to do it for him knowing it was possible.",
          "I created a MVP and not soon after the project kinda died.",
        ],
      },
      {
        id: "gjhmail",
        x: 300,
        y: 1000,
        width: 140,
        height: 90,
        title: "GJHMail Lore Pt.2",
        lines: [
          "Some time later the project came up again, and it was because my partners personal journey led him to really requiring some software to help his extremely busy schedule.",
          "He needed the project to be strictly tailored to how he and his clients are use to conducting work, for no one to notice any change",
          "but to have the whole process automated and being run in the backend.",
          "Currently out of 6 projects to be built and together to create the ultimate machine - 2 have been completed.",
        ],
      },
      {
        id: "gjhmail",
        x: 810,
        y: 572,
        width: 140,
        height: 90,
        title: "Email Ingestion",
        lines: [
          "Built Gmail push-notification listener with Google Pub/Sub.",
          "Instant email ingestion faster than it populates within the browser with zero polling.",
        ],
      },
      {
        id: "gjhmail",
        x: 960,
        y: 572,
        width: 140,
        height: 90,
        title: "PDF + AI Parser",
        lines: [
          "Designed AI-powered PDF extractor for a multitude of different documents",
          "Using regex and AI, the script determines what Schema and SubSchema workflow to follow.",
          "Integrated using OpenAI to identify and parse specific information and store in an Object.",
        ],
      },
      {
        id: "gjhmail",
        x: 1110,
        y: 572,
        width: 140,
        height: 90,
        title: "Doc Generator",
        lines: [
          "Auto-fills DOCX templates using",
          "Docxtemplater + structured JSON.",
        ],
      },
      {
        id: "gjhmail",
        x: 1260,
        y: 572,
        width: 140,
        height: 90,
        title: "Reply Engine",
        lines: [
          "Automatically self sends newly generated documents via Gmail API.",
          "Sent emails and included attachments are named accordingly for standardization and ease of understanding the email.",
          "And pre set reply drafts for quick review and sends.",
        ],
      },
    ],
  },

  university: {
    id: "university",
    title: "University",
    description: "Campus life and early projects. Walk to terminals to read.",
    backgroundClass: "world-bg-university",
    playerSkin: "nexus",
    width: 1600,
    height: 1300,
    spawn: { x: 400, y: 900 },
    collectibles: [
      {
        id: "degree-1",
        label: "Degree",
        icon: "✧",
        x: 560,
        y: 790,
        width: 18,
        height: 18,
      },
      {
        id: "degree-2",
        label: "Cap",
        icon: "✧",
        x: 1210,
        y: 970,
        width: 18,
        height: 18,
      },
      {
        id: "degree-3",
        label: "Gown",
        icon: "✧",
        x: 910,
        y: 490,
        width: 18,
        height: 18,
      },
    ],
    blockedZones: [
      { x: 0, y: 0, width: 1600, height: 220 },
      { x: 0, y: 220, width: 220, height: 1080 },
      { x: 1380, y: 220, width: 220, height: 1080 },
    ],
    terminals: [
      {
        id: "university",
        x: 500,
        y: 820,
        width: 140,
        height: 90,
        title: "University of Houston",
        lines: [
          "I graduated from University of Houston in 2022.",
          "I got a B.S in Computer Science, and also minored in Mathematics.",
          "I had a 3.3 gpa.",
          "Whos House? COOGS HOUSE.",
        ],
      },
      {
        id: "university",
        x: 850,
        y: 520,
        width: 140,
        height: 90,
        title: "Projects",
        lines: [
          "Since my biggest interest at the time and might still be video game development.",
          "I focused most of my Advanced Electives in Video Game Development courses and ended up developing two games for my capstone.",
          "I created a 3D VR shooter called Chrono Spel, and a 2D pixelated top down pointer shooter called Hemo Globin",
        ],
      },
      {
        id: "university",
        x: 1150,
        y: 1000,
        width: 140,
        height: 90,
        title: "Extras",
        lines: [
          "I was a part of Lebanese Students Assossiation (LSA).",
          "What made school memorable was sitting in the 8th floor of the library with all my buddies in between class.",
          "Covid ruined a year of school.",
        ],
      },
    ],
  },
  trial10: {
    id: "trial10",
    title: "Trial Gate",
    description: "For those with a strong will.",
    backgroundClass: "world-bg-nexus",
    playerSkin: "nexus",
    width: 1400,
    height: 1000,
    spawn: { x: 700, y: 700 },
  },
  badgehall: {
    id: "badgehall",
    title: "Badge Hall",
    description: "For those who collected every badge.",
    backgroundClass: "world-bg-nexus",
    playerSkin: "nexus",
    width: 1400,
    height: 1000,
    spawn: { x: 700, y: 700 },
    terminals: [
      {
        id: "badgehall-shrine",
        awardRightKey: true,
        x: 630,
        y: 590,
        width: 140,
        height: 90,
        title: "Badge Shrine",
        lines: [
          "You explored every world and collected every badge.",
          "Your curiosity and dedication have been recognized.",
          "Thank you for taking the time to read Matthew's full story.",
          "Right Half of the Master Key obtained.",
        ],
      },
    ],
  },
  mastergate: {
    id: "mastergate",
    title: "Master Gate",
    description: "Finis.",
    backgroundClass: "world-bg-nexus",
    playerSkin: "nexus",
    width: 1400,
    height: 1000,
    spawn: { x: 700, y: 700 },
    terminals: [
      {
        id: "mastergate-final",
        x: 630,
        y: 590,
        width: 140,
        height: 90,
        title: "From Matthew",
        lines: [
          "You made it.",
          "You passed the trial, collected every badge, and explored every corner of my world.",
          "Thank you so much for playing my portfolio — it genuinely means everything.",
          "If you'd like to work together, I'd love to build something great with you.",
          "— Matthew Klayme",
        ],
      },
    ],
  },
};
